[custom]
# 設置規則與基礎標誌位
enable_rule_generator=true
overwrite_original_rules=true
add_emoji=true
remove_old_emoji=true

# ==================== 規則集 (ruleset) ====================
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=📺 Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
ruleset=⚙️ 开发者,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Developer.list
ruleset=⚙️ 开发者,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list
ruleset=🔞 R18,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=🖼️ Pixiv,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pixiv.list
ruleset=Disney+,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
ruleset=✈️ Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
ruleset=🪟 巨硬服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
ruleset=🪟 巨硬服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OneDrive.list
ruleset=🎮 Xbox,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list
ruleset=🕹︎ Nintendo,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🖥️ PC游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🖥️ PC游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🖥️ PC游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Blizzard.list
ruleset=🤖 AI相关,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 AI相关,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Claude.list
ruleset=🤖 AI相关,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ClaudeAI.list
ruleset=🤖 AI相关,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Gemini.list
ruleset=🛒 Amazon,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Amazon.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIpV6.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ChinaDNS.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ChinaNet.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=DIRECT,https://raw.githubusercontent.com/xianyu-one/subconverter-toolkit/main/rule-list/remote.list
ruleset=DIRECT,https://raw.githubusercontent.com/xianyu-one/subconverter-toolkit/main/rule-list/cn-cloud.list
ruleset=DIRECT,https://raw.githubusercontent.com/xianyu-one/subconverter-toolkit/main/rule-list/cn-dbsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/xianyu-one/subconverter-toolkit/main/rule-list/plex-noproxy.list
ruleset=DIRECT,https://raw.githubusercontent.com/xianyu-one/subconverter-toolkit/main/rule-list/UnBan.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐟 漏网之鱼,[]FINAL

# ==================== 節點圖示 (emoji) ====================
emoji=(?i:Bandwidth|expire|流量|时间|应急|过期),🏳️‍🌈
emoji=(?i:\bHK[G]?\b|Hong.*?Kong|\bHKT\b|\bHKBN\b|\bHGC\b|\bWTT\b|\bCMI\b|[^-]香港),🇭🇰
emoji=(?i:\bTW[N]?\b|Taiwan|新北|彰化|\bCHT\b|台湾|[^-]台|\bHINET\b),🇹🇼
emoji=(?i:\bSG[P]?\b|Singapore|新加坡|狮城|[^-]新),🇸🇬
emoji=(?i:\bJP[N]?\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日),🇯🇵
emoji=(?i:\bK[O]?R\b|Korea|首尔|韩|韓),🇰🇷
emoji=(?i:\bUS[A]?\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥),🇺🇸
emoji=(Ascension|阿森松),🇦🇨
emoji=(?i:\bUAE\b|Dubai|阿联酋|迪拜),🇦🇪
emoji=(阿尔巴尼亚|Albania),🇦🇱
emoji=(Argentina|阿根廷),🇦🇷
emoji=(Austria|Vienna|奥地利|维也纳),🇦🇹
emoji=(?i:\bAU[S]?\b|Australia|Sydney|澳大利亚|澳洲|悉尼),🇦🇺
emoji=(阿塞拜疆|Azerbaijan),🇦🇿
emoji=(波黑共和国|波士尼亚与赫塞哥维纳|Bosnia|Herzegovina),🇧🇦
emoji=(Belgium|比利时),🇧🇪
emoji=(保加利亚|Bulgaria),🇧🇬
emoji=(Brazil|Paulo|巴西|圣保罗),🇧🇷
emoji=(?i:\bCA[N]?\b|Canada|Toronto|Montreal|Vancouver|加拿大|蒙特利尔|温哥华|楓葉|枫叶),🇨🇦
emoji=(Switzerland|Zurich|瑞士|苏黎世),🇨🇭
emoji=(智利|Chile),🇨🇱
emoji=(Colombia|哥伦比亚),🇨🇴
emoji=(Costa Rica|哥斯达黎加),🇨🇷
emoji=(塞浦路斯|Cyprus),🇨🇾
emoji=(Czech|捷克),🇨🇿
emoji=(?i:\bDE[U]?\b|Germany|法兰克福|德(国|意志)|中德|^德$),🇩🇪
emoji=(?i:\bD[N]?K\b|Denmark|丹麦),🇩🇰
emoji=(爱沙尼亚|Estonia),🇪🇪
emoji=(埃及|Egypt),🇪🇬
emoji=(?i:\bES[P]?\b|Spain|西班牙),🇪🇸
emoji=(Europe|欧洲),🇪🇺
emoji=(Finland|Helsinki|芬兰|赫尔辛基),🇫🇮
emoji=(?i:\bFR[A]?\b|France|Paris|法国|巴黎),🇫🇷
emoji=(?i:\bUK\b|\bGB[R]?\b|England|United.*?Kingdom|London|英国|[^-]英|伦敦),🇬🇧
emoji=(希腊|Greece),🇬🇷
emoji=(格鲁吉亚|Georgia),🇬🇪
emoji=(克罗地亚|Croatia),🇭🇷
emoji=(Hungary|匈牙利),🇭🇺
emoji=(Indonesia|Jakarta|印尼|印度尼西亚|雅加达),🇮🇩
emoji=(Ireland|Dublin|爱尔兰|都柏林),🇮🇪
emoji=(Israel|以色列),🇮🇱
emoji=(马恩岛|Mann),🇮🇲
emoji=(?i:\bIN[D]?\b|India|Mumbai|印度|孟买|加尔各答|贾坎德|泰米尔纳德),🇮🇳
emoji=(伊朗|Iran),🇮🇷
emoji=(?i:\bIS[L]?\b|Iceland|冰岛),🇮🇸
emoji=(Italy|Milan|意大利|米兰),🇮🇹
emoji=(约旦|Jordan),🇯🇴
emoji=(肯尼亚|Kenya),🇰🇪
emoji=(吉尔吉斯斯坦|Kyrgyzstan),🇰🇬
emoji=(柬埔寨|Cambodia),🇰🇭
emoji=(North.*?Korea|朝鲜),🇰🇵
emoji=(哈萨克斯坦|Kazakhstan),🇰🇿
emoji=(立陶宛|Lietuvos),🇱🇹
emoji=(卢森堡|Luxemburg|Luxembourg),🇱🇺
emoji=(拉脱维亚|Latvia),🇱🇻
emoji=(Moldova|摩尔多瓦),🇲🇩
emoji=(北马其顿|Macedonia),🇲🇰
emoji=(蒙古|Монголулс|Mongolia),🇲🇳
emoji=(Macao|澳门|\bCTM\b),🇲🇴
emoji=(墨西哥|Mexico),🇲🇽
emoji=(Malaysia|马来|MY),🇲🇾
emoji=(尼日利亚|Nigeria),🇳🇬
emoji=(?i:\bNL[D]?\b|Netherlands|荷兰|阿姆斯特丹),🇳🇱
emoji=(挪威|Norway),🇳🇴
emoji=(新西兰|纽西兰|New Zealand),🇳🇿
emoji=(Philippines|菲律宾),🇵🇭
emoji=(Pakistan|巴基斯坦),🇵🇰
emoji=(?i:\bP[O]?L\b|Poland|波兰),🇵🇱
emoji=(巴拿马|Panama),🇵🇦
emoji=(秘鲁|Peru),🇵🇪
emoji=(葡萄牙|Portugal),🇵🇹
emoji=(Romania|罗马尼亚),🇷🇴
emoji=(塞尔维亚|Serbia),🇷🇸
emoji=(?i:\bRU[S]?\b|Russia|Moscow|Petersburg|Siberia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|[^-]俄),🇷🇺
emoji=(Arabia|沙特),🇸🇦
emoji=(Sweden|瑞典),🇸🇪
emoji=(斯洛文尼亚|Slovenia),🇸🇮
emoji=(斯洛伐克|Slovensko),🇸🇰
emoji=(Thailand|泰国|曼谷),🇹🇭
emoji=(突尼斯|Tunisia),🇹🇳
emoji=(Turkey|土耳其|伊斯坦布尔),🇹🇷
emoji=(乌拉圭|Uruguay),🇺🇾
emoji=(Vietnam|越南),🇻🇳
emoji=(Africa|南非),🇿🇦
emoji=(Ukraine|UA|乌克兰),🇺🇦
emoji=(Puerto.*?Rico|波多黎各),🇵🇷
emoji=(Ecuador|厄瓜多尔),🇪🇨
emoji=(Morocco|摩洛哥),🇲🇦
emoji=(Nigeria|尼日利亚),🇳🇬
emoji=(Nepal|尼泊尔),🇳🇵
emoji=(Bengal|孟加拉),🇧🇩
emoji=(?i:\bC[H]?N\b|China|back|回国|中国[^-]|江苏[^-]|北京[^-]|上海[^-]|广州[^-]|深圳[^-]|杭州[^-]|常州[^-]|徐州[^-]|青岛[^-]|宁波[^-]|镇江[^-]|成都[^-]|河北[^-]|山西[^-]|辽宁[^-]|吉林[^-]|黑龙江[^-]|江苏[^-]|浙江[^-]|安徽[^-]|福建[^-]|江西[^-]|山东[^-]|河南[^-]|湖北[^-]|湖南[^-]|广东[^-]|海南[^-]|四川[^-]|贵州[^-]|云南[^-]|陕西[^-]|甘肃[^-]|青海[^-]|内蒙古[^-]|广西[^-]|西藏[^-]|宁夏[^-]|新疆[^-]),🇨🇳

# ==================== 1. 基礎邏輯組 ====================
custom_proxy_group=🔰 节点选择`select`[]✈ 延迟最低`[]✈ 故障切换`[]🔒 私有出口选择`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]流媒体`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🔒 私有出口选择`select`(🔒私有|私有|链式代理第二跳)
custom_proxy_group=✈ 手动选择`select`.*
custom_proxy_group=✈ 手动选择 2`select`.*
custom_proxy_group=✈ 手动选择 3`select`.*
custom_proxy_group=✈ 延迟最低`url-test`.*`http://www.gstatic.com/generate_204`500
custom_proxy_group=✈ 故障切换`fallback`.*`http://www.gstatic.com/generate_204`500
custom_proxy_group=🚀 前置节点池`load-balance`^(?!.*(高倍率|防丢失|私有|链式代理第二跳|订阅)).*$`http://www.gstatic.com/generate_204`300`round-robin


# ==================== 2. 業務分配組 ====================
custom_proxy_group=🍎 苹果服务`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🪟 巨硬服务`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=Google`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=📺 Youtube`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=⚙️ 开发者`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🕹︎ Nintendo`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🖥️ PC游戏平台`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🎮 Xbox`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🤖 AI相关`select`[]🔰 节点选择`[]🇺🇸 美国`[]🇹🇼 台湾地区`[]🇸🇬 新加坡`[]🇹🇼🇸🇬 中文地区`[]流媒体`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇯🇵 日本国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🖼️ Pixiv`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇯🇵 日本国`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=✈️ Telegram`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=🛒 Amazon`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇺🇸 美国`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇯🇵 日本国`[]🇹🇼 台湾地区`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇹🇼 台湾地区`[]🔰 节点选择`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]✈ 延迟最低`[]✈ 故障切换`(台)
custom_proxy_group=🔞 R18`select`[]🔰 节点选择`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇯🇵 日本国`[]🇭🇰 香港地区`[]🇸🇬 新加坡`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🇹🇼🇸🇬 中文地区`[]🪙超低倍率`[]DIRECT
custom_proxy_group=Disney+`select`[]🔰 节点选择`[]🇸🇬 新加坡`[]🇹🇼 台湾地区`[]🇹🇼🇸🇬 中文地区`[]流媒体`[]🇺🇸 美国`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇯🇵 日本国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🪙超低倍率`[]DIRECT
custom_proxy_group=Netflix`select`[]🔰 节点选择`[]🇹🇼🇸🇬 中文地区`[]流媒体`[]🇸🇬 新加坡`[]🇹🇼 台湾地区`[]🇺🇸 美国`[]✈ 延迟最低`[]✈ 故障切换`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]🇭🇰 香港地区`[]🇯🇵 日本国`[]🇩🇪 德国`[]🇦🇺 澳大利亚`[]🌏 东亚、东南亚`[]🌏 中东`[]🌍 欧洲`[]🇺🇸🇨🇦 北美通用`[]🪙超低倍率`[]DIRECT


# ==================== 3. 負載均衡地區組 (sticky-sessions) ====================
custom_proxy_group=🇭🇰 香港地区`load-balance`(?i)(港|HK|Hong)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🇸🇬 新加坡`load-balance`(?i)(新加坡|R新|s新|SG|Singapore)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🇺🇸 美国`load-balance`(?i)(美|US|United States)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🇩🇪 德国`load-balance`(?i)(德|Germany)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🇦🇺 澳大利亚`load-balance`(?i)(澳|Australia)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🇹🇼 台湾地区`load-balance`(台)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🇯🇵 日本国`load-balance`(日)`http://www.gstatic.com/generate_204`500`sticky-sessions
custom_proxy_group=🌏 东亚、东南亚`url-test`(?i)(台|新|日|韩|马来|印度|澳大利亚|新西兰|柬埔寨|巴基斯坦)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🌏 中东`url-test`(土耳其)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🌍 欧洲`url-test`(?i)(英|法|德|阿姆斯特丹|荷兰|比利时|瑞士)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇺🇸🇨🇦 北美通用`url-test`(?i)(美|加拿)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇹🇼🇸🇬 中文地区`url-test`(?i)(台|新)`http://www.gstatic.com/generate_204`500
custom_proxy_group=流媒体`url-test`(?i)(R台|s台|R新|s新|流|流媒体)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🪙超低倍率`load-balance`(0.2|0.3)`http://www.gstatic.com/generate_204`500`sticky-sessions

# ==================== 4. 兜底與直連組 ====================
custom_proxy_group=🌏 全球直连`select`[]DIRECT`[]🔰 节点选择`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]✈ 延迟最低`[]✈ 故障切换
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🔰 节点选择`[]✈ 手动选择`[]✈ 手动选择 2`[]✈ 手动选择 3`[]✈ 延迟最低`[]✈ 故障切换`[]DIRECT
