FROM ghcr.io/metacubex/subconverter:latest

COPY server_conf/include /base/include
COPY server_conf/all_base.tpl /base/base/all_base.tpl
COPY server_conf/emoji.toml /base/snippets/emoji.toml
COPY server_conf/pref.toml /base/pref.toml
COPY all-online.ini /base/config/all-online.ini
COPY lite-online.ini /base/config/lite-online.ini
